version: "3.7"
services:
  iptorrents-api:
    image: "node:12"
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./server:/home/node/app
      - ./puppeteer:/home/node/database
    ports:
      - "3001:3000"
    command: "npm run dev"

  iptorrents-client:
    image: "node:12"
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./client:/home/node/app
    ports:
      - "3000:8080"
    command: "npm run serve"

  iptorrents-cron:
    build:
      context: ./puppeteer
      dockerfile: ./Dockerfile
    volumes:
      - ./puppeteer:/app
    working_dir: /app
    command: bash -c "npm install && cron && tail -f /var/log/cron.log"
